-- "Add Element" catalog for the Planos floor-plan editor, modeled on
-- SystemSurveyor's categorized element picker (see
-- planos-add-element-implementacion.md). Replaces the flat 9-item
-- EQUIPMENT_TYPES list with 8 categories / ~232 elements. Fire Alarm,
-- Facility Equipment, and Healthcare are intentionally excluded per
-- product decision — not part of OTESS's current install scope.
--
-- element_types is a global read-only catalog (same shape as cable_types).
-- floor_plan_markers gets element_id (FK into the catalog) plus
-- serial_number/notes/quantity fields the marker popup now edits.
-- equipment_type/model/custom_icon_id are kept as-is for backward
-- compatibility with markers placed before this migration; the backfill
-- below assigns element_id to every existing marker so old and new
-- markers render through the same code path from day one.
--
-- Safe to re-run: guarded with IF NOT EXISTS / ON CONFLICT DO NOTHING.

create table if not exists element_types (
  id serial primary key,
  ss_element_id integer,          -- SystemSurveyor's own element id, for reference only; null when the source doc gave no id. NOT unique — SystemSurveyor reuses the same id for shared generic elements (Computer, Battery, General Component/Assembly/Software, Video Doorbell) across multiple categories, and so do we.
  system_name text not null,     -- "Video Surveillance"
  system_abbr text not null,     -- "VSS"
  system_color text not null,    -- "#faaf40"
  name text not null,            -- "Fixed Camera"
  abbr text not null,            -- "FCAM-" prefix for auto-generated marker labels
  icon_key text,                 -- key into EQUIPMENT_TYPES (app/equipmentIcons.js) when this element reuses an existing hand-drawn icon; null = render the category icon
  supports_aoc boolean not null default false,  -- can show an AOC (field of view) cone
  sort_order integer not null,
  is_active boolean not null default true
);

comment on table element_types is 'Catalog of placeable Planos elements, grouped by system/category (SystemSurveyor-style). Read-only reference data.';

create unique index if not exists element_types_system_name_name_idx on element_types (system_name, name);

-- RLS: same "shared read-only catalog" pattern as cable_types — everyone with
-- Planos access can read it, nobody edits it from the app.
alter table element_types enable row level security;
drop policy if exists "element_types_select_all" on element_types;
create policy "element_types_select_all" on element_types for select using (true);

alter table floor_plan_markers
  add column if not exists element_id integer references element_types(id),
  add column if not exists serial_number text,
  add column if not exists notes text,
  add column if not exists quantity integer not null default 1;

alter table floor_plan_markers alter column equipment_type drop not null;

-- ── Seed data ────────────────────────────────────────────────────────────
-- One INSERT per category, in the doc's original order (categories 6/8/11
-- skipped). ss_element_id is populated where the source doc gave an explicit
-- SystemSurveyor id (VSS, ACS, Infrastructure); the other categories were
-- listed as name-only in the doc, so ss_element_id is left null and a
-- reasonable abbr was generated by hand.

insert into element_types (ss_element_id, system_name, system_abbr, system_color, name, abbr, sort_order) values
-- 1. Video Surveillance (VSS) — #faaf40
(68,  'Video Surveillance', 'VSS', '#faaf40', 'Node', 'NODE-', 1001),
(69,  'Video Surveillance', 'VSS', '#faaf40', 'Fixed Camera', 'FCAM-', 1002),
(71,  'Video Surveillance', 'VSS', '#faaf40', 'PTZ Camera', 'PTZ-', 1003),
(257, 'Video Surveillance', 'VSS', '#faaf40', 'Multi-Lens Camera', 'MCAM-', 1004),
(72,  'Video Surveillance', 'VSS', '#faaf40', 'Server', 'SVR-', 1005),
(150, 'Video Surveillance', 'VSS', '#faaf40', 'Equipment Rack', 'RACK-', 1006),
(181, 'Video Surveillance', 'VSS', '#faaf40', 'Cable Balun', 'CBAL-', 1007),
(198, 'Video Surveillance', 'VSS', '#faaf40', 'Network Surge Protector', 'NTSP-', 1008),
(205, 'Video Surveillance', 'VSS', '#faaf40', 'PoE Injector', 'POEI-', 1009),
(227, 'Video Surveillance', 'VSS', '#faaf40', 'VSS Power Supply', 'VSPS-', 1010),
(88,  'Video Surveillance', 'VSS', '#faaf40', 'User Workstation', 'WKST-', 1011),
(73,  'Video Surveillance', 'VSS', '#faaf40', 'UPS Power Unit', 'UPS-', 1012),
(66,  'Video Surveillance', 'VSS', '#faaf40', 'Network Switch', 'NSW-', 1013),
(94,  'Video Surveillance', 'VSS', '#faaf40', 'Network Patch Panel', 'NPP-', 1014),
(166, 'Video Surveillance', 'VSS', '#faaf40', 'Network Jack', 'NJCK-', 1015),
(67,  'Video Surveillance', 'VSS', '#faaf40', 'VMS Software', 'VMS-', 1016),
(107, 'Video Surveillance', 'VSS', '#faaf40', 'Analog Video Encoder', 'VENC-', 1017),
(182, 'Video Surveillance', 'VSS', '#faaf40', 'Data Storage Array', 'DSA-', 1018),
(70,  'Video Surveillance', 'VSS', '#faaf40', 'NVR-DVR', 'NVR-', 1019),
(74,  'Video Surveillance', 'VSS', '#faaf40', 'Video Monitor', 'MON-', 1020),
(142, 'Video Surveillance', 'VSS', '#faaf40', 'Video Wall', 'VWLL-', 1021),
(235, 'Video Surveillance', 'VSS', '#faaf40', 'Microphone', 'MIC-', 1022),
(228, 'Video Surveillance', 'VSS', '#faaf40', 'IR Illuminator', 'IRIL-', 1023),
(93,  'Video Surveillance', 'VSS', '#faaf40', 'License Plate Reader', 'LPR-', 1024),
(86,  'Video Surveillance', 'VSS', '#faaf40', 'Wireless Access Point', 'WAP-', 1025),
(90,  'Video Surveillance', 'VSS', '#faaf40', 'Speaker', 'SPK-', 1026),
(259, 'Video Surveillance', 'VSS', '#faaf40', 'Video Doorbell', 'VDBL-', 1027),
(89,  'Video Surveillance', 'VSS', '#faaf40', 'Computer', 'CMPT-', 1028),
(206, 'Video Surveillance', 'VSS', '#faaf40', 'Battery', 'BAT-', 1029),
(95,  'Video Surveillance', 'VSS', '#faaf40', 'General Component', 'GEN-', 1030),
(96,  'Video Surveillance', 'VSS', '#faaf40', 'General Assembly', 'GASM-', 1031),
(258, 'Video Surveillance', 'VSS', '#faaf40', 'General Multi-Sensor Device', 'GMSD-', 1032),
(262, 'Video Surveillance', 'VSS', '#faaf40', 'General Software', 'GSWT-', 1033),

-- 2. Access Control (ACS) — #00a650
(165, 'Access Control', 'ACS', '#00a650', 'Node', 'NODE-', 2001),
(177, 'Access Control', 'ACS', '#00a650', 'Automatic Door Operator', 'ADOP-', 2002),
(203, 'Access Control', 'ACS', '#00a650', 'Pedestrian Entry', 'PED-', 2003),
(164, 'Access Control', 'ACS', '#00a650', 'Server', 'SVR-', 2004),
(120, 'Access Control', 'ACS', '#00a650', 'Double Door', 'DDR-', 2005),
(116, 'Access Control', 'ACS', '#00a650', 'Single Door', 'SNDR-', 2006),
(163, 'Access Control', 'ACS', '#00a650', 'User Workstation', 'WKST-', 2007),
(170, 'Access Control', 'ACS', '#00a650', 'UPS Power Unit', 'UPS-', 2008),
(168, 'Access Control', 'ACS', '#00a650', 'Network Switch', 'NSW-', 2009),
(171, 'Access Control', 'ACS', '#00a650', 'Network Patch Panel', 'NPP-', 2010),
(115, 'Access Control', 'ACS', '#00a650', 'Card Reader', 'CRDR-', 2011),
(136, 'Access Control', 'ACS', '#00a650', 'Elec Lockset', 'ELOK-', 2012),
(130, 'Access Control', 'ACS', '#00a650', 'Panic Button', 'PNB-', 2013),
(122, 'Access Control', 'ACS', '#00a650', 'Biometric Reader', 'BIOR-', 2014),
(137, 'Access Control', 'ACS', '#00a650', 'Elec Exit Device', 'EEXT-', 2015),
(135, 'Access Control', 'ACS', '#00a650', 'Electric Strike', 'ESTR-', 2016),
(129, 'Access Control', 'ACS', '#00a650', 'Door Position Switch', 'DPSW-', 2017),
(128, 'Access Control', 'ACS', '#00a650', 'Magnetic Lock', 'MGLT-', 2018),
(127, 'Access Control', 'ACS', '#00a650', 'Request to Exit', 'REX-', 2019),
(131, 'Access Control', 'ACS', '#00a650', 'Motion Detector', 'MODT-', 2020),
(173, 'Access Control', 'ACS', '#00a650', 'Enclosure', 'ENCL-', 2021),
(119, 'Access Control', 'ACS', '#00a650', 'ACS Software', 'ACSS-', 2022),
(132, 'Access Control', 'ACS', '#00a650', 'ACS Power Supply', 'ACSP-', 2023),
(133, 'Access Control', 'ACS', '#00a650', 'ACS Expansion Module', 'ACSM-', 2024),
(118, 'Access Control', 'ACS', '#00a650', 'ACS Controller', 'ACSC-', 2025),
(161, 'Access Control', 'ACS', '#00a650', 'Intercom Master Station', 'ICMS-', 2026),
(162, 'Access Control', 'ACS', '#00a650', 'Intercom End Point', 'ICEP-', 2027),
(175, 'Access Control', 'ACS', '#00a650', 'Relay', 'RLY-', 2028),
(176, 'Access Control', 'ACS', '#00a650', 'Tamper Switch', 'TMSW-', 2029),
(222, 'Access Control', 'ACS', '#00a650', 'Vehicle Gate Operator', 'VGO-', 2030),
(223, 'Access Control', 'ACS', '#00a650', 'Vehicle Entry Control Point', 'VECP-', 2031),
(255, 'Access Control', 'ACS', '#00a650', 'Turnstile', 'TSTL-', 2032),
(256, 'Access Control', 'ACS', '#00a650', 'Overhead Door', 'OVHD-', 2033),
(184, 'Access Control', 'ACS', '#00a650', 'Door Prop Alarm', 'DPRP-', 2034),
(204, 'Access Control', 'ACS', '#00a650', 'Pedestrian Metal Detector', 'PMDT-', 2035),
(230, 'Access Control', 'ACS', '#00a650', 'Badging Printer', 'BDGP-', 2036),
(174, 'Access Control', 'ACS', '#00a650', 'Power Transfer Device', 'PTD-', 2037),
(232, 'Access Control', 'ACS', '#00a650', 'Visitor Kiosk', 'VKSK-', 2038),
(117, 'Access Control', 'ACS', '#00a650', 'AC Keypad', 'KPDS-', 2039),
(169, 'Access Control', 'ACS', '#00a650', 'Wireless Receiver Hub', 'WRCV-', 2040),
(134, 'Access Control', 'ACS', '#00a650', 'Alarm Sounder', 'ALSD-', 2041),
(253, 'Access Control', 'ACS', '#00a650', 'Long Range Reader', 'LGRR-', 2042),
(246, 'Access Control', 'ACS', '#00a650', 'Emergency Door Release', 'EDR-', 2043),
(248, 'Access Control', 'ACS', '#00a650', 'Health Scan Kiosk', 'HSK-', 2044),
(259, 'Access Control', 'ACS', '#00a650', 'Video Doorbell', 'VDBL-', 2045),
(260, 'Access Control', 'ACS', '#00a650', 'Handicap Push Button', 'HPBT-', 2046),
(261, 'Access Control', 'ACS', '#00a650', 'ID Scanner', 'IDSC-', 2047),
(263, 'Access Control', 'ACS', '#00a650', 'Garage Door Operator', 'GDO-', 2048),
(264, 'Access Control', 'ACS', '#00a650', 'Door Holdback', 'DHB-', 2049),
(89,  'Access Control', 'ACS', '#00a650', 'Computer', 'CMPT-', 2050),
(231, 'Access Control', 'ACS', '#00a650', 'Printer', 'PRNT-', 2051),
(206, 'Access Control', 'ACS', '#00a650', 'Battery', 'BAT-', 2052),
(224, 'Access Control', 'ACS', '#00a650', 'Generator', 'GNR-', 2053),
(95,  'Access Control', 'ACS', '#00a650', 'General Component', 'GEN-', 2054),
(96,  'Access Control', 'ACS', '#00a650', 'General Assembly', 'GASM-', 2055),
(262, 'Access Control', 'ACS', '#00a650', 'General Software', 'GSWT-', 2056),

-- 3. Intrusion Detection (IDS) — #f15a24 (name-only in source doc, abbrs generated)
(null, 'Intrusion Detection', 'IDS', '#f15a24', 'Motion Detector', 'MODT-', 3001),
(null, 'Intrusion Detection', 'IDS', '#f15a24', 'Door Position Switch', 'DPSW-', 3002),
(null, 'Intrusion Detection', 'IDS', '#f15a24', 'Glass Break Detector', 'GBDT-', 3003),
(null, 'Intrusion Detection', 'IDS', '#f15a24', 'Panic Button', 'PNB-', 3004),
(null, 'Intrusion Detection', 'IDS', '#f15a24', 'Vibration Sensor', 'VIBS-', 3005),
(null, 'Intrusion Detection', 'IDS', '#f15a24', 'Perimeter Beam', 'PBM-', 3006),
(null, 'Intrusion Detection', 'IDS', '#f15a24', 'Passive IR Detector', 'PIRD-', 3007),
(null, 'Intrusion Detection', 'IDS', '#f15a24', 'Dual Technology Detector', 'DTDT-', 3008),
(null, 'Intrusion Detection', 'IDS', '#f15a24', 'IDS Control Panel', 'IDSCP-', 3009),
(null, 'Intrusion Detection', 'IDS', '#f15a24', 'IDS Expander Module', 'IDSM-', 3010),
(null, 'Intrusion Detection', 'IDS', '#f15a24', 'IDS Power Supply', 'IDSP-', 3011),
(null, 'Intrusion Detection', 'IDS', '#f15a24', 'IDS Software', 'IDSS-', 3012),
(null, 'Intrusion Detection', 'IDS', '#f15a24', 'Keypad', 'KPD-', 3013),
(null, 'Intrusion Detection', 'IDS', '#f15a24', 'Siren', 'SRN-', 3014),
(null, 'Intrusion Detection', 'IDS', '#f15a24', 'Siren Strobe', 'SRNS-', 3015),
(null, 'Intrusion Detection', 'IDS', '#f15a24', 'Alarm Sounder', 'ALSD-', 3016),
(null, 'Intrusion Detection', 'IDS', '#f15a24', 'Relay', 'RLY-', 3017),
(null, 'Intrusion Detection', 'IDS', '#f15a24', 'Tamper Switch', 'TMSW-', 3018),
(null, 'Intrusion Detection', 'IDS', '#f15a24', 'Universal Transmitter', 'UNTX-', 3019),
(null, 'Intrusion Detection', 'IDS', '#f15a24', 'Cellular Communicator', 'CELC-', 3020),
(null, 'Intrusion Detection', 'IDS', '#f15a24', 'End of Line', 'EOL-', 3021),
(null, 'Intrusion Detection', 'IDS', '#f15a24', 'Battery', 'BAT-', 3022),
(null, 'Intrusion Detection', 'IDS', '#f15a24', 'Generator', 'GNR-', 3023),
(null, 'Intrusion Detection', 'IDS', '#f15a24', 'General Component', 'GEN-', 3024),
(null, 'Intrusion Detection', 'IDS', '#f15a24', 'General Assembly', 'GASM-', 3025),
(null, 'Intrusion Detection', 'IDS', '#f15a24', 'General Software', 'GSWT-', 3026),

-- 4. Infrastructure (INFRA) — #ed1c24
(null, 'Infrastructure', 'INFRA', '#ed1c24', 'Node', 'NODE-', 4001),
(null, 'Infrastructure', 'INFRA', '#ed1c24', 'Cable Path', 'CP-', 4002),
(null, 'Infrastructure', 'INFRA', '#ed1c24', 'Equipment Rack', 'RACK-', 4003),
(null, 'Infrastructure', 'INFRA', '#ed1c24', 'Cable Balun', 'CBAL-', 4004),
(null, 'Infrastructure', 'INFRA', '#ed1c24', 'Network Surge Protector', 'NTSP-', 4005),
(null, 'Infrastructure', 'INFRA', '#ed1c24', 'PoE Injector', 'POEI-', 4006),
(null, 'Infrastructure', 'INFRA', '#ed1c24', 'Multimedia Outlet', 'MMO-', 4007),
(null, 'Infrastructure', 'INFRA', '#ed1c24', 'Junction Box', 'JBX-', 4008),
(null, 'Infrastructure', 'INFRA', '#ed1c24', 'UPS Power Unit', 'UPS-', 4009),
(null, 'Infrastructure', 'INFRA', '#ed1c24', 'Network Patch Panel', 'NPP-', 4010),
(null, 'Infrastructure', 'INFRA', '#ed1c24', 'Network Jack', 'NJCK-', 4011),
(null, 'Infrastructure', 'INFRA', '#ed1c24', 'Enclosure', 'ENCL-', 4012),
(null, 'Infrastructure', 'INFRA', '#ed1c24', 'Structured Media Cabinet', 'SMC-', 4013),
(null, 'Infrastructure', 'INFRA', '#ed1c24', 'Wireless Receiver Hub', 'WRCV-', 4014),
(null, 'Infrastructure', 'INFRA', '#ed1c24', 'Battery', 'BAT-', 4015),
(null, 'Infrastructure', 'INFRA', '#ed1c24', 'Generator', 'GNR-', 4016),
(null, 'Infrastructure', 'INFRA', '#ed1c24', 'General Component', 'GEN-', 4017),
(null, 'Infrastructure', 'INFRA', '#ed1c24', 'General Assembly', 'GASM-', 4018),

-- 5. Information Technology (IT) — #0072bc (name-only, abbrs generated)
(null, 'Information Technology', 'IT', '#0072bc', 'Node', 'NODE-', 5001),
(null, 'Information Technology', 'IT', '#0072bc', 'Server', 'SVR-', 5002),
(null, 'Information Technology', 'IT', '#0072bc', 'Equipment Rack', 'RACK-', 5003),
(null, 'Information Technology', 'IT', '#0072bc', 'Network Surge Protector', 'NTSP-', 5004),
(null, 'Information Technology', 'IT', '#0072bc', 'PoE Injector', 'POEI-', 5005),
(null, 'Information Technology', 'IT', '#0072bc', 'Network Firewall', 'NFW-', 5006),
(null, 'Information Technology', 'IT', '#0072bc', 'User Workstation', 'WKST-', 5007),
(null, 'Information Technology', 'IT', '#0072bc', 'UPS Power Unit', 'UPS-', 5008),
(null, 'Information Technology', 'IT', '#0072bc', 'Network Router', 'NRTR-', 5009),
(null, 'Information Technology', 'IT', '#0072bc', 'Network Switch', 'NSW-', 5010),
(null, 'Information Technology', 'IT', '#0072bc', 'Network Patch Panel', 'NPP-', 5011),
(null, 'Information Technology', 'IT', '#0072bc', 'Network Jack', 'NJCK-', 5012),
(null, 'Information Technology', 'IT', '#0072bc', 'Data Storage Array', 'DSA-', 5013),
(null, 'Information Technology', 'IT', '#0072bc', 'Biometric Reader', 'BIOR-', 5014),
(null, 'Information Technology', 'IT', '#0072bc', 'Video Monitor', 'MON-', 5015),
(null, 'Information Technology', 'IT', '#0072bc', 'Wireless Access Point', 'WAP-', 5016),
(null, 'Information Technology', 'IT', '#0072bc', 'Badging Printer', 'BDGP-', 5017),
(null, 'Information Technology', 'IT', '#0072bc', 'Visitor Kiosk', 'VKSK-', 5018),
(null, 'Information Technology', 'IT', '#0072bc', 'Universal Transmitter', 'UNTX-', 5019),
(null, 'Information Technology', 'IT', '#0072bc', 'Health Scan Kiosk', 'HSK-', 5020),
(null, 'Information Technology', 'IT', '#0072bc', 'ID Scanner', 'IDSC-', 5021),
(null, 'Information Technology', 'IT', '#0072bc', 'Computer', 'CMPT-', 5022),
(null, 'Information Technology', 'IT', '#0072bc', 'Printer', 'PRNT-', 5023),
(null, 'Information Technology', 'IT', '#0072bc', 'Cellular Communicator', 'CELC-', 5024),
(null, 'Information Technology', 'IT', '#0072bc', 'Battery', 'BAT-', 5025),
(null, 'Information Technology', 'IT', '#0072bc', 'Generator', 'GNR-', 5026),
(null, 'Information Technology', 'IT', '#0072bc', 'General Component', 'GEN-', 5027),
(null, 'Information Technology', 'IT', '#0072bc', 'General Assembly', 'GASM-', 5028),
(null, 'Information Technology', 'IT', '#0072bc', 'General Software', 'GSWT-', 5029),

-- 6. Audio Visual (AV) — #0072bc (name-only, abbrs generated)
(null, 'Audio Visual', 'AV', '#0072bc', 'Node', 'NODE-', 6001),
(null, 'Audio Visual', 'AV', '#0072bc', 'Server', 'SVR-', 6002),
(null, 'Audio Visual', 'AV', '#0072bc', 'Equipment Rack', 'RACK-', 6003),
(null, 'Audio Visual', 'AV', '#0072bc', 'Multimedia Outlet', 'MMO-', 6004),
(null, 'Audio Visual', 'AV', '#0072bc', 'User Workstation', 'WKST-', 6005),
(null, 'Audio Visual', 'AV', '#0072bc', 'Network Switch', 'NSW-', 6006),
(null, 'Audio Visual', 'AV', '#0072bc', 'Network Jack', 'NJCK-', 6007),
(null, 'Audio Visual', 'AV', '#0072bc', 'Enclosure', 'ENCL-', 6008),
(null, 'Audio Visual', 'AV', '#0072bc', 'Structured Media Cabinet', 'SMC-', 6009),
(null, 'Audio Visual', 'AV', '#0072bc', 'Projection Screen', 'PSCR-', 6010),
(null, 'Audio Visual', 'AV', '#0072bc', 'Projector', 'PROJ-', 6011),
(null, 'Audio Visual', 'AV', '#0072bc', 'TV Monitor Lift', 'TVML-', 6012),
(null, 'Audio Visual', 'AV', '#0072bc', 'Video Conference System', 'VCS-', 6013),
(null, 'Audio Visual', 'AV', '#0072bc', 'Television', 'TV-', 6014),
(null, 'Audio Visual', 'AV', '#0072bc', 'Video Monitor', 'MON-', 6015),
(null, 'Audio Visual', 'AV', '#0072bc', 'Microphone Outlet', 'MICO-', 6016),
(null, 'Audio Visual', 'AV', '#0072bc', 'Speaker', 'SPK-', 6017),
(null, 'Audio Visual', 'AV', '#0072bc', 'Amplifier', 'AMP-', 6018),
(null, 'Audio Visual', 'AV', '#0072bc', 'DSP Processor', 'DSP-', 6019),
(null, 'Audio Visual', 'AV', '#0072bc', 'Streaming Device', 'STRD-', 6020),
(null, 'Audio Visual', 'AV', '#0072bc', 'Display', 'DISP-', 6021),
(null, 'Audio Visual', 'AV', '#0072bc', 'Video Wall', 'VWLL-', 6022),
(null, 'Audio Visual', 'AV', '#0072bc', 'Microphone', 'MIC-', 6023),
(null, 'Audio Visual', 'AV', '#0072bc', 'Computer', 'CMPT-', 6024),
(null, 'Audio Visual', 'AV', '#0072bc', 'Battery', 'BAT-', 6025),
(null, 'Audio Visual', 'AV', '#0072bc', 'General Component', 'GEN-', 6026),
(null, 'Audio Visual', 'AV', '#0072bc', 'General Assembly', 'GASM-', 6027),
(null, 'Audio Visual', 'AV', '#0072bc', 'General Software', 'GSWT-', 6028),

-- 7. Communications (COMM) — #00bcd4 (name-only, abbrs generated)
(null, 'Communications', 'COMM', '#00bcd4', 'Node', 'NODE-', 7001),
(null, 'Communications', 'COMM', '#00bcd4', 'Server', 'SVR-', 7002),
(null, 'Communications', 'COMM', '#00bcd4', 'Equipment Rack', 'RACK-', 7003),
(null, 'Communications', 'COMM', '#00bcd4', 'User Workstation', 'WKST-', 7004),
(null, 'Communications', 'COMM', '#00bcd4', 'UPS Power Unit', 'UPS-', 7005),
(null, 'Communications', 'COMM', '#00bcd4', 'Network Switch', 'NSW-', 7006),
(null, 'Communications', 'COMM', '#00bcd4', 'Network Jack', 'NJCK-', 7007),
(null, 'Communications', 'COMM', '#00bcd4', 'Panic Button', 'PNB-', 7008),
(null, 'Communications', 'COMM', '#00bcd4', 'Intercom Master Station', 'ICMS-', 7009),
(null, 'Communications', 'COMM', '#00bcd4', 'Intercom End Point', 'ICEP-', 7010),
(null, 'Communications', 'COMM', '#00bcd4', 'Intercom Power Supply', 'ICPS-', 7011),
(null, 'Communications', 'COMM', '#00bcd4', 'Public Address Amp', 'PAAMP-', 7012),
(null, 'Communications', 'COMM', '#00bcd4', 'Public Address Speaker', 'PASPK-', 7013),
(null, 'Communications', 'COMM', '#00bcd4', 'Video Doorbell', 'VDBL-', 7014),
(null, 'Communications', 'COMM', '#00bcd4', 'Cellular Communicator', 'CELC-', 7015),
(null, 'Communications', 'COMM', '#00bcd4', 'Two-Way Radio', 'TWR-', 7016),
(null, 'Communications', 'COMM', '#00bcd4', 'Emergency Call Station', 'ECS-', 7017),
(null, 'Communications', 'COMM', '#00bcd4', 'Battery', 'BAT-', 7018),
(null, 'Communications', 'COMM', '#00bcd4', 'Generator', 'GNR-', 7019),
(null, 'Communications', 'COMM', '#00bcd4', 'General Component', 'GEN-', 7020),
(null, 'Communications', 'COMM', '#00bcd4', 'General Assembly', 'GASM-', 7021),
(null, 'Communications', 'COMM', '#00bcd4', 'General Software', 'GSWT-', 7022),

-- 8. Building Management (BMS) — #9c27b0 (name-only, abbrs generated)
(null, 'Building Management', 'BMS', '#9c27b0', 'Node', 'NODE-', 8001),
(null, 'Building Management', 'BMS', '#9c27b0', 'Server', 'SVR-', 8002),
(null, 'Building Management', 'BMS', '#9c27b0', 'User Workstation', 'WKST-', 8003),
(null, 'Building Management', 'BMS', '#9c27b0', 'UPS Power Unit', 'UPS-', 8004),
(null, 'Building Management', 'BMS', '#9c27b0', 'Network Switch', 'NSW-', 8005),
(null, 'Building Management', 'BMS', '#9c27b0', 'Thermostat', 'THRM-', 8006),
(null, 'Building Management', 'BMS', '#9c27b0', 'HVAC Controller', 'HVAC-', 8007),
(null, 'Building Management', 'BMS', '#9c27b0', 'BMS Controller', 'BMSC-', 8008),
(null, 'Building Management', 'BMS', '#9c27b0', 'Temperature Sensor', 'TMPS-', 8009),
(null, 'Building Management', 'BMS', '#9c27b0', 'Humidity Sensor', 'HUMS-', 8010),
(null, 'Building Management', 'BMS', '#9c27b0', 'Occupancy Sensor', 'OCCS-', 8011),
(null, 'Building Management', 'BMS', '#9c27b0', 'Light Switch', 'LSW-', 8012),
(null, 'Building Management', 'BMS', '#9c27b0', 'Light Keypad', 'LKPD-', 8013),
(null, 'Building Management', 'BMS', '#9c27b0', 'Utility Meter', 'UMTR-', 8014),
(null, 'Building Management', 'BMS', '#9c27b0', 'Relay', 'RLY-', 8015),
(null, 'Building Management', 'BMS', '#9c27b0', 'Battery', 'BAT-', 8016),
(null, 'Building Management', 'BMS', '#9c27b0', 'Generator', 'GNR-', 8017),
(null, 'Building Management', 'BMS', '#9c27b0', 'General Component', 'GEN-', 8018),
(null, 'Building Management', 'BMS', '#9c27b0', 'General Assembly', 'GASM-', 8019),
(null, 'Building Management', 'BMS', '#9c27b0', 'General Software', 'GSWT-', 8020)
on conflict (system_name, name) do nothing;

-- ── icon_key: reuse OTESS's existing hand-drawn icons for the elements that
-- map 1:1 to the old EQUIPMENT_TYPES keys (see mapping table below). Every
-- other element falls back to its category icon at render time.
update element_types set icon_key = 'camera'         where name = 'Fixed Camera'          and system_name = 'Video Surveillance';
update element_types set icon_key = 'access_control'  where name = 'Card Reader'            and system_name = 'Access Control';
update element_types set icon_key = 'access_point'    where name = 'Wireless Access Point'  and system_name = 'Information Technology';
update element_types set icon_key = 'door_contact'    where name = 'Door Position Switch'   and system_name = 'Intrusion Detection';
update element_types set icon_key = 'keypad'          where name = 'AC Keypad'              and system_name = 'Access Control';
update element_types set icon_key = 'nvr_dvr'         where name = 'NVR-DVR'                and system_name = 'Video Surveillance';
update element_types set icon_key = 'motion_sensor'   where name = 'Motion Detector'        and system_name = 'Intrusion Detection';
update element_types set icon_key = 'speaker'         where name = 'Speaker'                and system_name = 'Audio Visual';
update element_types set icon_key = 'rack'            where name = 'Equipment Rack'         and system_name = 'Infrastructure';

-- ── supports_aoc: elements that can meaningfully show a field-of-view cone
-- (cameras, WAPs, motion-type intrusion sensors) across every category they
-- appear in.
update element_types set supports_aoc = true where name in (
  'Fixed Camera', 'PTZ Camera', 'Multi-Lens Camera', 'Video Doorbell', 'License Plate Reader',
  'Wireless Access Point',
  'Motion Detector', 'Passive IR Detector', 'Dual Technology Detector', 'Perimeter Beam'
);

-- ── Backfill existing markers so they resolve through the new catalog
-- (mapping table from planos-add-element-implementacion.md):
update floor_plan_markers set element_id = (select id from element_types where name = 'Fixed Camera' and system_name = 'Video Surveillance') where equipment_type = 'camera' and element_id is null;
update floor_plan_markers set element_id = (select id from element_types where name = 'Card Reader' and system_name = 'Access Control') where equipment_type = 'access_control' and element_id is null;
update floor_plan_markers set element_id = (select id from element_types where name = 'Wireless Access Point' and system_name = 'Information Technology') where equipment_type = 'access_point' and element_id is null;
update floor_plan_markers set element_id = (select id from element_types where name = 'Door Position Switch' and system_name = 'Intrusion Detection') where equipment_type = 'door_contact' and element_id is null;
update floor_plan_markers set element_id = (select id from element_types where name = 'AC Keypad' and system_name = 'Access Control') where equipment_type = 'keypad' and element_id is null;
update floor_plan_markers set element_id = (select id from element_types where name = 'NVR-DVR' and system_name = 'Video Surveillance') where equipment_type = 'nvr_dvr' and element_id is null;
update floor_plan_markers set element_id = (select id from element_types where name = 'Motion Detector' and system_name = 'Intrusion Detection') where equipment_type = 'motion_sensor' and element_id is null;
update floor_plan_markers set element_id = (select id from element_types where name = 'Speaker' and system_name = 'Audio Visual') where equipment_type = 'speaker' and element_id is null;
update floor_plan_markers set element_id = (select id from element_types where name = 'Equipment Rack' and system_name = 'Infrastructure') where equipment_type = 'rack' and element_id is null;
