-- Flags an estimate line item as generated by the "Calcular cable/tubo"
-- modal (app/CableCalculator.js). The first material in a calculator batch
-- becomes a normal item and the rest attach to it as accessories, always
-- combined into that one line (no "Combinar precios" toggle — there's
-- nothing to choose). This column lets the edit form hide that toggle for
-- these items and lets the read-only estimate skip its title-based grouping
-- path for them, since they already collapse via the accessory relationship.
--
-- Safe to re-run: add column if not exists.

alter table estimate_line_items add column if not exists from_calculator boolean not null default false;
